name: Backend-Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container: python:{{cookiecutter.python_version}}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install --no-install-recommends -y binutils libproj-dev gdal-bin python-gdal
          python -m pip install --upgrade pip
          pip install -r {{cookiecutter.project_name}}/requirements.txt
      - name: Run Django Tests
        run: |
          python {{cookiecutter.project_name}}/manage.py test
  
  deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    needs: build
    steps:
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_SERVER_IP }}
          username: ${{ secrets.STAGE_SERVER_USERNAME }}
          key: ${{ secrets.STAGE_SSHKEY }}
          script: >
            cd ${{ secrets.STAGE_PROJECT_PATH }}
            && git pull 
            && ./mng-api.sh up